handler: dl#opal.OpalServer
appname: HelloService
servicename: api
language: javascript
libs: ['core@>0.9.0', 'dl@>0.9.0', 'rewire@1.0.3'] 
sdk_version: 1
version: '0.1'
interfaces:
  public:
    authentication: false
    authorisation: false
    ssl: false
